---
apiVersion: v1
kind: Service
metadata:
  name: proxmox-sso
spec:
  selector:
    app.kubernetes.io/name: proxmox-sso
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
