---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-ceph-cosi-system-classes
  namespace: flux-system
spec:
  path: ./kubernetes/apps/ceph-cosi-system/classes/app
  dependsOn:
    - name: cluster-apps-external-secrets
    - name: cluster-apps-ceph-cosi
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
