apiVersion: apps/v1
kind: Deployment
metadata:
  name: objectstorage-provisioner
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: driver-ceph
    app.kubernetes.io/version: main
    app.kubernetes.io/name: cosi-driver-ceph
spec:
  template:
    spec:
      containers:
        - name: objectstorage-provisioner-sidecar
          image: "gcr.io/k8s-staging-sig-storage/objectstorage-sidecar:v20241219-v0.1.0-60-g6a5a12c"
        - name: ceph-cosi-driver
          image: "quay.io/ceph/cosi:v0.1.2"
