apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: qbittorrent
    app.kubernetes.io/name: qbittorrent-torrent
    app.kubernetes.io/service: qbittorrent-torrent
  name: qbittorrent-torrent
spec:
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  ports:
  - name: torrent
    nodePort: 30741
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app.kubernetes.io/component: qbittorrent
    app.kubernetes.io/instance: qbittorrent
    app.kubernetes.io/name: qbittorrent
  sessionAffinity: None
  type: LoadBalancer
