---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  INGRESS_CLASS: traefik
  DOMAIN: "deangalvin.dev"
  TIMEZONE: "America/New_York"
  PRODUCTION_TLS: "deangalvin-dev-production-tls"
  DEANGALVIN_DEV_PRODUCTION_TLS: "deangalvin-dev-production-tls"
  GLIMMERLABS_IO_PRODUCTION_TLS: "glimmerlabs-io-production-tls"
  ARCLOG_COM_PRODUCTION_TLS: "arclog-com-production-tls"
