---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "https://github.com/ceph/ceph-cosi/?ref=2ae8b22035e7cbdbac1db24293df866700fa7910"

patchesStrategicMerge:
  - overlay/delete-namespace.yaml
  #- overlay/deployment.yaml
