---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./authelia.yaml
  - ./authentik.yaml
  - ./backube.yaml
  - ./bjw-s.yaml
  - ./cloudnative-pg.yaml
  - ./crossplane.yaml
  - ./elastic.yaml
  - ./emberstack.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./freekingdean.yaml
  - ./glauth.yaml
  - ./grafana.yaml
  - ./hajimari.yaml
  - ./istio.yaml
  - ./jaeger.yaml
  - ./jetstack.yaml
  - ./kubernetes-dashboard.yaml
  - ./kyverno.yaml
  - ./metallb.yaml
  - ./onepassword-connect.yaml
  - ./piraeus.yaml
  - ./prometheus-community.yaml
  - ./redfish-exporter.yaml
  - ./rook.yaml
  - ./stakater.yaml
  - ./traefik.yaml
