---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: replica-block
provisioner: rbd.csi.ceph.com
parameters:
  clusterID: ceph
  pool: data-pool
  imageFormat: "2"
  imageFeatures: layering
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/controller-expand-secret-name: &secretName csi-rbd-credentials
  csi.storage.k8s.io/controller-expand-secret-namespace: &secretNamespace ceph-csi-rbd
  csi.storage.k8s.io/controller-publish-secret-name: *secretName
  csi.storage.k8s.io/controller-publish-secret-namespace: *secretNamespace
  csi.storage.k8s.io/node-stage-secret-name: *secretName
  csi.storage.k8s.io/node-stage-secret-namespace: *secretNamespace
  csi.storage.k8s.io/provisioner-secret-name: *secretName
  csi.storage.k8s.io/provisioner-secret-namespace: *secretNamespace
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
