---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: filebrowser-static-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: filebrowser-static-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        filebrowser.yaml: |
          auth:
            methods:
              oidc:
                enabled: true
                clientId: {{ .client_id }}
                clientSecret: {{ .client_secret }}
                issuerUrl: "https://authentik.deangalvin.dev/application/o/file-browser/"
                scopes: "email openid profile groups"
                userIdentifier: "preferred_username"
                createUser: true
  data:
    - secretKey: client_id
      remoteRef:
        key: authentik-filebrowser
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: authentik-filebrowser
        property: client_secret
