---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials-external
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafana-admin-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ADMIN_USER: "{{ .username }}"
        ADMIN_PASSWORD: "{{ .password }}"
  dataFrom:
    - extract:
        key: grafana-admin-credentials
