---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ghost
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.0.14
      sourceRef:
        kind: HelmRepository
        name: freekingdean
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      ghost:
        containers:
          ghost:
            envFrom:
              - secretRef:
                  name: ghost-secret
    stateful: true
    image:
      repository: docker.io/library/ghost
      tag: 6.16.1
    env:
      database__client: mysql
      database__connection__host: ghost-mariadb.arcolog.svc.cluster.local
      database__connection__user: ghost
      database__connection__database: ghost
      mail__transport: SMTP
      mail__from: no-reply@glimmerlabs.io
      mail__options__service: Mailgun
      mail__options__auth__user: no-reply@glimmerlabs.io
      TZ: America/New_York
      url: "https://www.arcolog.com"
      admin__url: "https://www.arcolog.com"
    ports:
      http: 2368
    ingress:
      subdomain: arcolog
      localonly: false
      icon: "mdi:television-classic"
    persistence:
      config:
        type: persistentVolumeClaim
        existingClaim: ghost-config
        globalMounts:
          - path: /var/lib/ghost/content
    serviceMonitor:
      enabled: false
