---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "https://github.com/kubernetes-sigs/container-object-storage-interface?ref=release-0.2"
patchesStrategicMerge:
  - overlay/delete-namespace.yaml
