apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/instance: ghost
    app.kubernetes.io/name: ghost
  name: ghost-public
spec:
  ingressClassName: traefik
  rules:
  - host: blog.arclog.com
    http:
      paths:
      - backend:
          service:
            name: ghost
            port:
              number: 2368
        path: /
        pathType: Prefix
  - host: www.arclog.com
    http:
      paths:
      - backend:
          service:
            name: ghost
            port:
              number: 2368
        path: /
        pathType: Prefix
  - host: arclog.com
    http:
      paths:
      - backend:
          service:
            name: ghost
            port:
              number: 2368
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - arclog.com
    secretName: arclog-com-production-tls
