---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name ghost-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    template:
      data:
        # Ghost
        database__connection__password: "{{ .GHOST_DB_PASSWORD }}"
        # DB
        mariadb-root-password: "{{ .GHOST_DB_ROOT_PASSWORD }}"
        mariadb-password: "{{ .GHOST_DB_PASSWORD }}"
  dataFrom:
  - extract:
      key: ghost
