---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-external
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authentik-external
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AUTHENTIK_SECRET_KEY: "{{ .secret_key }}"
        AUTHENTIK_BOOTSTRAP_PASSWORD: "{{ .bootstrap_password }}"
        AUTHENTIK_BOOTSTRAP_TOKEN: "{{ .bootstrap_token }}"
        AUTHENTIK_BOOTSTRAP_EMAIL: "{{ .bootstrap_email }}"
  dataFrom:
    - extract:
        key: authentik
