kind: BucketAccessClass
apiVersion: objectstorage.k8s.io/v1alpha1
metadata:
  name: ceph
driverName: cosi.ceph.objectstorage.k8s.io
authenticationType: KEY
parameters:
  objectStoreUserSecretName: bucket-access-admin-credentials
  objectStoreUserSecretNamespace: ceph-cosi-system
