---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bucket-access-admin-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: bucket-access-admin-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AccessKey: "{{ .rgw_access_key }}"
        SecretKey: "{{ .rgw_secret_key }}"
        Endpoint: "http://10.0.0.104:7480"
  dataFrom:
    - extract:
        key: ceph-csi-credentials
