---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ceph-csi-cephfs
spec:
  interval: 15m
  chart:
    spec:
      chart: ceph-csi-cephfs
      version: 3.16.1
      sourceRef:
        kind: HelmRepository
        name: ceph-csi
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    csiConfig:
      - clusterID: "ceph"
        monitors: &monitors
          - "10.0.0.104"
          - "10.0.0.105"
          - "10.0.0.106"
          - "10.0.0.107"
        cephFS:
          subvolumeGroup: "csi"
      - clusterID: "ceph_ec"
        monitors: *monitors
        cephFS:
          subvolumeGroup: "csi_ec"
